# Generated by Django 3.2.6 on 2021-08-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_of_dish',
            field=models.CharField(choices=[('H', 'лл')], max_length=1),
        ),
    ]
