# Generated by Django 3.2.6 on 2021-08-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_type_of_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_of_dish',
            field=models.CharField(choices=[('В', 'Выпечка'), ('Д', 'Десерты'), ('З', 'Закуски'), ('Н', 'Напитки'), ('С', 'Салаты'), ('С', 'Супы'), ('О', 'Основное блюдо')], max_length=1),
        ),
    ]
