# Generated by Django 3.2.6 on 2021-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('Шеф-повар', 'Шеф-повар'), ('Повар', 'Повар'), ('Любитель', 'Любитель'), ('Домохозяйка', 'Домохозяйка')], max_length=15),
        ),
    ]
