# Generated by Django 3.2.7 on 2021-09-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210914_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('is_publicated', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='news')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Советы',
                'ordering': ['title'],
            },
        ),
    ]
