# Generated by Django 3.2.7 on 2021-09-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_advice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
    ]
