# Generated by Django 3.2.6 on 2021-08-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='location',
            new_name='short_description',
        ),
    ]
