# Generated by Django 3.2.7 on 2021-09-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20210914_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='level',
            field=models.CharField(choices=[('Вторые блюда', 'Блюда из суппродуктов'), ('Выпечка', 'Выпечка'), ('Десерт', 'Десерт'), ('Закуски', 'Закуски')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
