# Generated by Django 3.2.6 on 2021-09-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='level',
            field=models.CharField(choices=[('Вторые блюда', 'Вторые блюда'), ('Выпечка', 'Выпечка'), ('Десерт', 'Десерт'), ('Закуски', 'Закуски'), ('Супы', 'Супы'), ('Салаты', 'Салаты')], max_length=15),
        ),
    ]
